name: "ChatGPT Reviewer"
author: "Pengfei Ni"
description: "Automated pull requests reviewing and issues triaging with ChatGPT"
inputs:
  GITHUB_TOKEN:
    description: "Github token used to send out review comments"
    required: true
  OPENAI_API_KEY:
    description: "API key used to invoke OpenAI"
    required: true
  OPENAI_API_BASE:
    description: "API based used to access [Azure] OpenAI API"
    required: false
  model:
    description: "OpenAI model name"
    default: "gpt-4"
    required: false
  temperature:
    description: "Temperature for the model"
    default: '0.2'
    required: false
  frequency_penalty:
    description: "Frequency penalty for the model"
    default: '0'
    required: false
  presence_penalty:
    description: "Presence penalty for the model"
    default: '0'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --model=${{ inputs.model }}
  - --temperature=${{ inputs.temperature }}
  - --frequency-penalty=${{ inputs.frequency_penalty }}
  - --presence-penalty=${{ inputs.presence_penalty }}
branding:
  icon: 'compass'
  color: 'blue'